obj-m := hello_world_mod.o
CFLAGS_hello_world_module_2.o := -U__HELLO_DEBUG__
hello_world_mod-objs := hello_world_module_1.o  hello_world_module_2.o
DEBUG_FLAGS := -DDEBUG
ccflags-y := -I$(src)/../common $(DEBUG_FLAGS)
ccflags-y += -D__HELLO_DEBUG__
